# Generated by Django 2.1.1 on 2018-09-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trans',
            new_name='Tran',
        ),
    ]
